export var sdpArray = [
	{
		id: '1000',
		type: 'service',
		name: 'ServiceDiscoveryServerServiceClassID',
	}, {
		id: '1001',
		type: 'service',
		name: 'BrowseGroupDescriptorServiceClassID',
	}, {
		id: '1101',
		type: 'service',
		name: 'SerialPort',
		abbr: 'spp'
	}, {
		id: '1102',
		type: 'service',
		name: 'LANAccessUsingPPP',
		abbr: 'lan'
	}, {
		id: '1103',
		type: 'service',
		name: 'DialupNetworking',
		abbr: 'dun'
	}, {
		id: '1104',
		type: 'service',
		name: 'IrMCSync',
		abbr: 'sync'
	}, {
		id: '1105',
		type: 'service',
		name: 'OBEXObjectPush',
		abbr: 'opp'
	}, {
		id: '1106',
		type: 'service',
		name: 'OBEXFileTransfer',
		abbr: 'ftp'
	}, {
		id: '1107',
		type: 'service',
		name: 'IrMCSyncCommand',
		abbr: 'sync'
	}, {
		id: '1108',
		type: 'service',
		name: 'Headset',
		abbr: 'hsp'
	}, {
		id: '1109',
		type: 'service',
		name: 'CordlessTelephony',
		abbr: 'ctp'
	}, {
		id: '110a',
		type: 'service',
		name: 'AudioSource',
		abbr: 'a2dp'
	}, {
		id: '110b',
		type: 'service',
		name: 'AudioSink',
		abbr: 'a2dp'
	}, {
		id: '110c',
		type: 'service',
		name: 'A/V_RemoteControlTarget',
		abbr: 'avrcp'
	}, {
		id: '110d',
		type: 'service',
		name: 'AdvancedAudioDistribution',
		abbr: 'a2dp'
	}, {
		id: '110e',
		type: 'service',
		name: 'A/V_RemoteControl',
		abbr: 'avrcp'
	}, {
		id: '110f',
		type: 'service',
		name: 'A/V_RemoteControlController',
		abbr: 'avrcp'
	}, {
		id: '1110',
		type: 'service',
		name: 'Intercom',
		abbr: 'icp'
	}, {
		id: '1111',
		type: 'service',
		name: 'Fax',
		abbr: 'fax'
	}, {
		id: '1112',
		type: 'service',
		name: 'Headset - Audio Gateway (AG)',
		abbr: 'hsp'
	}, {
		id: '1113',
		type: 'service',
		name: 'WAP',
	}, {
		id: '1114',
		type: 'service',
		name: 'WAP_CLIENT',
	}, {
		id: '1115',
		type: 'service',
		name: 'PANU',
		abbr: 'pan'
	}, {
		id: '1116',
		type: 'service',
		name: 'NAP',
		abbr: 'pan'
	}, {
		id: '1117',
		type: 'service',
		name: 'GN',
		abbr: 'pan'
	}, {
		id: '1118',
		type: 'service',
		name: 'DirectPrinting',
		abbr: 'bpp'
	}, {
		id: '1119',
		type: 'service',
		name: 'ReferencePrinting',
		abbr: 'bpp'
	}, {
		id: '111a',
		type: 'service',
		name: 'Basic Imaging Profile',
		abbr: 'bip'
	}, {
		id: '111b',
		type: 'service',
		name: 'ImagingResponder',
		abbr: 'bip'
	}, {
		id: '111c',
		type: 'service',
		name: 'ImagingAutomaticArchive',
		abbr: 'bip'
	}, {
		id: '111d',
		type: 'service',
		name: 'ImagingReferencedObjects',
		abbr: 'bip'
	}, {
		id: '111e',
		type: 'service',
		name: 'Handsfree',
		abbr: 'hfp'
	}, {
		id: '111f',
		type: 'service',
		name: 'HandsfreeAudioGateway',
		abbr: 'hfp'
	}, {
		id: '1120',
		type: 'service',
		name: 'DirectPrintingReferenceObjectsService',
		abbr: 'bpp'
	}, {
		id: '1121',
		type: 'service',
		name: 'ReflectedUI',
		abbr: 'bpp'
	}, {
		id: '1122',
		type: 'service',
		name: 'BasicPrinting',
		abbr: 'bpp'
	}, {
		id: '1123',
		type: 'service',
		name: 'PrintingStatus',
		abbr: 'bpp'
	}, {
		id: '1124',
		type: 'service',
		name: 'HumanInterfaceDeviceService',
		abbr: 'hid'
	}, {
		id: '1125',
		type: 'service',
		name: 'HardcopyCableReplacement',
		abbr: 'hcrp'
	}, {
		id: '1126',
		type: 'service',
		name: 'HCR_Print',
		abbr: 'hcrp'
	}, {
		id: '1127',
		type: 'service',
		name: 'HCR_Scan',
		abbr: 'hcrp'
	}, {
		id: '1128',
		type: 'service',
		name: 'Common_ISDN_Access',
		abbr: 'cip'
	}, {
		id: '112d',
		type: 'service',
		name: 'SIM_Access',
		abbr: 'sap'
	}, {
		id: '112e',
		type: 'service',
		name: 'Phonebook Access - PCE',
		abbr: 'pbap'
	}, {
		id: '112f',
		type: 'service',
		name: 'Phonebook Access - PSE',
		abbr: 'pbap'
	}, {
		id: '1130',
		type: 'service',
		name: 'Phonebook Access',
		abbr: 'pbap'
	}, {
		id: '1131',
		type: 'service',
		name: 'Headset - HS',
		abbr: 'hsp'
	}, {
		id: '1132',
		type: 'service',
		name: 'Message Access Server',
		abbr: 'map'
	}, {
		id: '1133',
		type: 'service',
		name: 'Message Notification Server',
		abbr: 'map'
	}, {
		id: '1134',
		type: 'service',
		name: 'Message Access Profile',
		abbr: 'map'
	}, {
		id: '1135',
		type: 'service',
		name: 'GNSS',
		abbr: 'gnss'
	}, {
		id: '1136',
		type: 'service',
		name: 'GNSS_Server',
		abbr: 'gnss'
	}, {
		id: '1137​',
		type: 'service',
		name: '​3D Display',
		abbr: '​3dsp'
	}, {
		type: 'service',
		name: '​3D Glasses',
		id: '​0x1138',
		abbr: '​3dsp'
	}, {
		id: '1139​',
		type: 'service',
		name: '​3D Synchronization',
		abbr: '​3dsp'
	}, {
		type: 'service',
		name: '​MPS Profile UUID',
		id: '​0x113a',
		abbr: '​mps'
	}, {
		type: 'service',
		name: '​MPS SC UUID',
		id: '​0x113b',
		abbr: '​mps'
	}, {
		type: 'service',
		name: '​CTN Access Service​',
		id: '​0x113c​',
		abbr: '​ctn'
	}, {
		type: 'service',
		name: '​CTN Notification Service​',
		id: '​0x113d',
		abbr: '​​ctn'
	}, {
		type: 'service',
		name: '​CTN Profile',
		id: '​0x113e',
		abbr: '​​ctn'
	}, {
		id: '1200',
		type: 'service',
		name: 'PnPInformation',
		abbr: 'did'
	}, {
		id: '1201',
		type: 'service',
		name: 'GenericNetworking',
	}, {
		id: '1202',
		type: 'service',
		name: 'GenericFileTransfer',
	}, {
		id: '1203',
		type: 'service',
		name: 'GenericAudio',
	}, {
		id: '1204',
		type: 'service',
		name: 'GenericTelephony',
	}, {
		id: '1205',
		type: 'service',
		name: 'UPNP_Service',
		abbr: 'esdp'
	}, {
		id: '1206',
		type: 'service',
		name: 'UPNP_IP_Service',
		abbr: 'esdp'
	}, {
		id: '1300',
		type: 'service',
		name: 'ESDP_UPNP_IP_PAN',
		abbr: 'esdp'
	}, {
		id: '1301',
		type: 'service',
		name: 'ESDP_UPNP_IP_LAP',
		abbr: 'esdp'
	}, {
		id: '1302',
		type: 'service',
		name: 'ESDP_UPNP_L2CAP',
		abbr: 'esdp'
	}, {
		id: '1303',
		type: 'service',
		name: 'VideoSource',
		abbr: 'vdp'
	}, {
		id: '1304',
		type: 'service',
		name: 'VideoSink',
		abbr: 'vdp'
	}, {
		id: '1305',
		type: 'service',
		name: 'VideoDistribution',
		abbr: 'vdp'
	}, {
		id: '1400',
		type: 'service',
		name: 'HDP',
		abbr: 'hdp'
	}, {
		id: '1401',
		type: 'service',
		name: 'HDP Source',
		abbr: 'hdp'
	}, {
		id: '1402',
		type: 'service',
		name: 'HDP Sink',
		abbr: 'hdp'
	}, {
		id: '0000',
		type: 'attribute',
		name: 'ServiceRecordHandle'
	}, {
		id: '0001',
		type: 'attribute',
		name: 'ServiceClassIDList'
	}, {
		id: '0002',
		type: 'attribute',
		name: 'ServiceRecordState'
	}, {
		id: '0003',
		type: 'attribute',
		name: 'ServiceID'
	}, {
		id: '0004',
		type: 'attribute',
		name: 'ProtocolDescriptorList'
	}, {
		id: '0005',
		type: 'attribute',
		name: 'BrowseGroupList'
	}, {
		id: '0006',
		type: 'attribute',
		name: 'LanguageBaseAttributeIDList'
	}, {
		id: '0007',
		type: 'attribute',
		name: 'ServiceInfoTimeToLive'
	}, {
		id: '0008',
		type: 'attribute',
		name: 'ServiceAvailability'
	}, {
		id: '0009',
		type: 'attribute',
		name: 'BluetoothProfileDescriptorList'
	}, {
		id: '000a',
		type: 'attribute',
		name: 'DocumentationURL'
	}, {
		id: '000b',
		type: 'attribute',
		name: 'ClientExecutableURL'
	}, {
		id: '000c',
		type: 'attribute',
		name: 'IconURL'
	}, {
		id: '000d',
		type: 'attribute',
		name: 'AdditionalProtocolDescriptorLists'
	},
]